import { MarketCardProps } from "./types";

export const mockMarkets: MarketCardProps[] = [
  {
    id: "1",
    thumbnailUrl: "https://picsum.photos/seed/market1/100/100",
    title: "Will the Federal Reserve raise interest rates in Q1 2025?",
    type: "dateRows",
    rows: [
      {
        label: "January 2025",
        yesPriceCents: 64.5,
        noPriceCents: 35.5,
        yesEnabled: true,
        noEnabled: true,
      },
      {
        label: "February 2025",
        yesPriceCents: 58.2,
        noPriceCents: 41.8,
        yesEnabled: true,
        noEnabled: true,
      },
      {
        label: "March 2025",
        yesPriceCents: 72.8,
        noPriceCents: 27.2,
        yesEnabled: true,
        noEnabled: true,
      },
    ],
    volumeUSD: 2450000,
    actions: { gift: true, bookmark: true, notify: true },
  },
  {
    id: "2",
    thumbnailUrl: "https://picsum.photos/seed/market2/100/100",
    title: "2024 Presidential Election Winner",
    type: "candidates",
    items: [
      { name: "Candidate A", percent: 52.3 },
      { name: "Candidate B", percent: 38.7 },
      { name: "Candidate C", percent: 6.8 },
      { name: "Other", percent: 2.2 },
    ],
    volumeUSD: 15750000,
    actions: { bookmark: true, notify: true },
  },
  {
    id: "3",
    thumbnailUrl: "https://picsum.photos/seed/market3/100/100",
    title: "Will Bitcoin reach $100,000 before end of 2025?",
    type: "dateRows",
    rows: [
      {
        label: "By Q1 2025",
        yesPriceCents: 28.5,
        noPriceCents: 71.5,
        yesEnabled: true,
        noEnabled: true,
      },
      {
        label: "By Q2 2025",
        yesPriceCents: 45.2,
        noPriceCents: 54.8,
        yesEnabled: true,
        noEnabled: true,
      },
      {
        label: "By Q4 2025",
        yesPriceCents: 68.9,
        noPriceCents: 31.1,
        yesEnabled: true,
        noEnabled: true,
      },
    ],
    volumeUSD: 8920000,
    actions: { gift: true, bookmark: true },
  },
  {
    id: "4",
    thumbnailUrl: "https://picsum.photos/seed/market4/100/100",
    title: "NFL Super Bowl LIX Winner",
    type: "candidates",
    items: [
      { name: "Kansas City Chiefs", percent: 18.5 },
      { name: "San Francisco 49ers", percent: 16.2 },
      { name: "Philadelphia Eagles", percent: 12.8 },
      { name: "Buffalo Bills", percent: 11.3 },
      { name: "Other", percent: 41.2 },
    ],
    volumeUSD: 4560000,
    actions: { bookmark: true, notify: true },
  },
  {
    id: "5",
    thumbnailUrl: "https://picsum.photos/seed/market5/100/100",
    title: "Will AI achieve AGI (Artificial General Intelligence) by 2030?",
    type: "dateRows",
    rows: [
      {
        label: "By 2026",
        yesPriceCents: 8.5,
        noPriceCents: 91.5,
        yesEnabled: true,
        noEnabled: true,
      },
      {
        label: "By 2028",
        yesPriceCents: 22.7,
        noPriceCents: 77.3,
        yesEnabled: true,
        noEnabled: true,
      },
      {
        label: "By 2030",
        yesPriceCents: 38.4,
        noPriceCents: 61.6,
        yesEnabled: true,
        noEnabled: true,
      },
    ],
    volumeUSD: 6780000,
    actions: { gift: true, bookmark: true, notify: true },
  },
  {
    id: "6",
    thumbnailUrl: "https://picsum.photos/seed/market6/100/100",
    title: "Best Picture Oscar 2025",
    type: "candidates",
    items: [
      { name: "Oppenheimer", percent: 42.8 },
      { name: "Killers of the Flower Moon", percent: 28.5 },
      { name: "Poor Things", percent: 15.7 },
      { name: "The Zone of Interest", percent: 8.2 },
      { name: "Other", percent: 4.8 },
    ],
    volumeUSD: 1250000,
    actions: { bookmark: true },
  },
];
